baseURL = 'https://davidmm01.github.io/recipebook/'
# https://discourse.gohugo.io/t/publication-on-github-pages-and-baseurl/43631
languageCode = 'en-us'
sectionPagesMenu = "main"
theme = 'recipebooktheme'
title = 'My New Hugo Site'
[menu]
[[menu.main]]
name = "Home"
pre = "home"
url = "/"
weight = 1
[[menu.main]]
name = "Posts"
pre = "pen-tool"
url = "/posts/"
weight = 2
[[menu.main]]
name = "Tags"
pre = "tag"
url = "/tags/"
weight = 3
