baseURL = 'https://davidmm01.github.io/recipebook/'
# baseURL = 'http://example.org/'
# https://discourse.gohugo.io/t/publication-on-github-pages-and-baseurl/43631
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'mytheme'
[taxonomies]
  category = 'categories'
  tag = 'tags'
  cusineo = 'cusine'
